const games_data = [
	{
		id: 1,
		sport: "Women’s Soccer",
		opponent: "#19 Michigan",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-09-21",
		time: "7:00 p.m.",
		points: 8,
	},
	{
		id: 2,
		sport: "Women’s Volleyball",
		opponent: "#1 Wisconsin",
		location: "Welsh-Ryan Arena",
		date: "2023-09-22",
		time: "7:00 p.m.",
		points: 8,
	},
	{
		id: 3,
		sport: "Men’s Football",
		opponent: "Minnesota",
		location: "Ryan Field",
		date: "2023-09-23",
		time: "6:30 p.m.",
		points: 3,
	},
	{
		id: 4,
		sport: "Women’s Field Hockey",
		opponent: "#17 Princeton",
		location: "Lakeside Field",
		date: "2023-09-24",
		time: "11:00 p.m.",
		points: 6,
	},
	{
		id: 5,
		sport: "Men’s Soccer",
		opponent: "Ohio State",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-09-24",
		time: "1:00 p.m.",
		points: 4,
	},
	{
		id: 6,
		sport: "Women’s Volleyball",
		opponent: "#15 Penn State",
		location: "Welsh-Ryan Arena",
		date: "2023-09-24",
		time: "1:00 p.m.",
		points: 6,
	},
	{
		id: 7,
		sport: "Women’s Soccer",
		opponent: "Illinois",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-09-28",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 8,
		sport: "Women’s Field Hockey",
		opponent: "Michigan State",
		location: "Lakeside Field",
		date: "2023-09-29",
		time: "3:00 p.m.",
		points: 4,
	},
	{
		id: 9,
		sport: "Women’s Volleyball",
		opponent: "Michigan State",
		location: "Welsh-Ryan Arena",
		date: "2023-09-29",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 10,
		sport: "Men’s Football",
		opponent: "#6 Penn State",
		location: "Ryan Field",
		date: "2023-09-30",
		time: "11:00 a.m.",
		points: 3,
	},
	{
		id: 11,
		sport: "Women’s Field Hockey",
		opponent: "#15 Michigan",
		location: "Lakeside Field",
		date: "2023-10-01",
		time: "11:00 a.m.",
		points: 4,
	},
	{
		id: 12,
		sport: "Women’s Soccer",
		opponent: "Nebraska",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-01",
		time: "2:00 p.m.",
		points: 4,
	},
	{
		id: 13,
		sport: "Men’s Soccer",
		opponent: "Green Bay",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-03",
		time: "6:00 p.m.",
		points: 4,
	},
	{
		id: 14,
		sport: "Men’s Football",
		opponent: "Howard",
		location: "Ryan Field",
		date: "2023-10-07",
		time: "2:00 p.m.",
		points: 4,
	},
	{
		id: 15,
		sport: "Men’s Soccer",
		opponent: "Rutgers",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-08",
		time: "1:00 p.m.",
		points: 4,
	},
	{
		id: 16,
		sport: "Women’s Volleyball",
		opponent: "Maryland",
		location: "Welsh-Ryan Arena",
		date: "2023-10-13",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 17,
		sport: "Women’s Volleyball",
		opponent: "Nebraska",
		location: "Welsh-Ryan Arena",
		date: "2023-10-18",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 18,
		sport: "Women’s Soccer",
		opponent: "Minnesota",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-19",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 19,
		sport: "Men’s Soccer",
		opponent: "Michigan State",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-20",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 20,
		sport: "Women’s Volleyball",
		opponent: "Michigan",
		location: "Welsh-Ryan Arena",
		date: "2023-10-21",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 21,
		sport: "Men’s Soccer",
		opponent: "Indiana",
		location: "Lanny and Sharon Martin Stadium",
		date: "2023-10-24",
		time: "7:00 p.m.",
		points: 4,
	},
	{
		id: 22,
		sport: "Women’s Field Hockey",
		opponent: "Maryland",
		location: "Lakeside Field",
		date: "2023-10-26",
		time: "3:00 p.m.",
		points: 4,
	},
	{
		id: 23,
		sport: "Men’s Football",
		opponent: "Maryland",
		location: "Ryan Field",
		date: "2023-10-28",
		time: "TBA",
		points: 3,
	},
];

export default games_data;
